services:
  - type: web
    name: voiceai
    env: python
    buildCommand: "pip install -r requirements.txt && cd demo && npm install && npm run build"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16