services:
  - type: web
    name: voiceai
    env: python
    buildCommand: "pip install -r requirements.txt && cd demo && npm ci --production=false && npm run build"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: NODE_VERSION
        value: 18.17.0